export interface Product {
  productId: string;
  name: string;
  brand: string;
  brandCountry: string;
  category: string;
  productType: string;
  description: string;
  ingredients: string;
  keyIngredients: string;
  skinTypes?: string;
  skinConcerns?: string;
  hairTypes?: string;
  hairConcerns?: string;
  price: number;
  size: string;
  rating: number;
  reviewCount: number;
  isKorean: boolean;
  isVegan: boolean;
  isCrueltyFree: boolean;
  imageUrl: string;
  imageUrlAlt?: string;
  officialUrl: string;
  yesStyleUrl?: string;
  amazonUrl?: string;
  sephoraUrl?: string;
}

export const products: Product[] = [
    // ==================== COSRX - K-Beauty ====================
    {
      productId: "COSRX-SNAIL-96-ESSENCE",
      name: "Advanced Snail 96 Mucin Power Essence",
      brand: "COSRX",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "essence",
      description: "Essenza concentrata al 96% di bava di lumaca per idratazione intensa e riparazione cutanea. Formulata con Snail Secretion Filtrate per una pelle più luminosa ed elastica.",
      ingredients: "Snail Secretion Filtrate, Betaine, Butylene Glycol, Sodium Hyaluronate, Panthenol, Allantoin, Arginine",
      keyIngredients: "Snail Mucin 96%, Hyaluronic Acid, Panthenol",
      skinTypes: "all, dry, sensitive, normal, combination",
      skinConcerns: "idratazione, anti-età, cicatrizzazione, arrossamenti, barriera cutanea",
      price: 25.90,
      size: "100ml",
      rating: 4.8,
      reviewCount: 2847,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://cosrx.com/cdn/shop/files/1_97b9ad1c-c7b1-42ae-b28c-f0f93df1b595.png?v=1706597847&width=600",
      imageUrlAlt: "https://cosrx.com/cdn/shop/products/COSRX_Advanced_Snail_96_Mucin_Power_Essence_100ml.png?v=1678870844&width=600",
      officialUrl: "https://cosrx.com/products/advanced-snail-96-mucin-power-essence",
      yesStyleUrl: "https://www.yesstyle.com/it/cosrx-advanced-snail-96-mucin-power-essence-100ml/info.html/pid.1046503834",
      amazonUrl: "https://www.amazon.it/dp/B00PBSZ9M0",
    },
    {
      productId: "COSRX-LOW-PH-CLEANSER",
      name: "Low pH Good Morning Gel Cleanser",
      brand: "COSRX",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "cleanser",
      description: "Detergente viso gel con pH 5.5, delicato ma efficace con BHA e tea tree oil. Perfetto per pelli sensibili e a tendenza acneica.",
      ingredients: "Water, Cocamidopropyl Betaine, Glycerin, Tea Tree Leaf Oil, Betaine Salicylate",
      keyIngredients: "Tea Tree Oil, BHA 0.5%, Betaine",
      skinTypes: "sensitive, oily, combination, acne-prone",
      skinConcerns: "detersione, pH equilibrato, acne, pelle grassa",
      price: 12.50,
      size: "150ml",
      rating: 4.6,
      reviewCount: 3421,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://cosrx.com/cdn/shop/files/1_70e4ebd4-9e4e-4d77-8b3c-fb4055c60963.png?v=1706597698&width=600",
      officialUrl: "https://cosrx.com/products/low-ph-good-morning-gel-cleanser",
      yesStyleUrl: "https://www.yesstyle.com/it/cosrx-low-ph-good-morning-gel-cleanser-150ml/info.html/pid.1046504006",
      amazonUrl: "https://www.amazon.it/dp/B01M0GB8CC",
    },
    {
      productId: "COSRX-AHA7-WHITEHEAD",
      name: "AHA 7 Whitehead Power Liquid",
      brand: "COSRX",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "exfoliant",
      description: "Esfoliante chimico con acido glicolico 7% per eliminare le cellule morte e migliorare la texture cutanea.",
      ingredients: "Water, Glycolic Acid, Butylene Glycol, Niacinamide",
      keyIngredients: "Glycolic Acid 7%, Niacinamide",
      skinTypes: "normal, combination, oily",
      skinConcerns: "texture, macchie, pori, punti bianchi",
      price: 25.00,
      size: "100ml",
      rating: 4.6,
      reviewCount: 2134,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://cosrx.com/cdn/shop/products/COSRX_AHA_7_Whitehead_Power_Liquid_100ml.png?v=1678870851&width=600",
      officialUrl: "https://cosrx.com/products/aha-7-whitehead-power-liquid",
      yesStyleUrl: "https://www.yesstyle.com/it/cosrx-aha-7-whitehead-power-liquid-100ml/info.html/pid.1046503896",
    },
    {
      productId: "COSRX-BHA-BLACKHEAD",
      name: "BHA Blackhead Power Liquid",
      brand: "COSRX",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "exfoliant",
      description: "Trattamento con acido salicilico 4% per punti neri e pori dilatati. Penetra nei pori per eliminare sebo e impurità.",
      ingredients: "Water, Betaine Salicylate, Butylene Glycol, Tea Tree Extract",
      keyIngredients: "Salicylic Acid 4%, Tea Tree Extract",
      skinTypes: "oily, combination, acne-prone",
      skinConcerns: "punti neri, pori, acne, sebo",
      price: 26.00,
      size: "100ml",
      rating: 4.5,
      reviewCount: 1892,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://cosrx.com/cdn/shop/products/COSRX_BHA_Blackhead_Power_Liquid_100ml.png?v=1678870853&width=600",
      officialUrl: "https://cosrx.com/products/bha-blackhead-power-liquid",
      yesStyleUrl: "https://www.yesstyle.com/it/cosrx-bha-blackhead-power-liquid-100ml/info.html/pid.1046503878",
    },

    // ==================== BEAUTY OF JOSEON - K-Beauty ====================
    {
      productId: "BOJ-RELIEF-SUN-SPF50",
      name: "Relief Sun: Rice + Probiotics SPF50+ PA++++",
      brand: "Beauty of Joseon",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "spf",
      description: "Crema solare leggera con estratto di riso 30% e probiotici, SPF50+ PA++++. Texture non appiccicosa, ideale come base trucco.",
      ingredients: "Water, Propanediol, Homosalate, Niacinamide, Rice Extract 30%",
      keyIngredients: "Rice Extract 30%, Niacinamide 2%, Probiotics",
      skinTypes: "all",
      skinConcerns: "protezione solare, anti-età, idratazione",
      price: 18.90,
      size: "50ml",
      rating: 4.9,
      reviewCount: 1567,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://beautyofjoseon.com/wp-content/uploads/2023/02/Relief-Sun-Rice-Probiotics-1.png",
      officialUrl: "https://beautyofjoseon.com/product/relief-sun-rice-probiotics/",
      yesStyleUrl: "https://www.yesstyle.com/it/beauty-of-joseon-relief-sun-rice-probiotics-spf50-pa-50ml/info.html/pid.1061515127",
      amazonUrl: "https://www.amazon.it/dp/B09V1NKL7C",
    },
    {
      productId: "BOJ-GINSENG-ESSENCE",
      name: "Ginseng Essence Water",
      brand: "Beauty of Joseon",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Essenza tonificante con 80% estratto di ginseng rosso coreano. Antiossidante e idratante.",
      ingredients: "Panax Ginseng Root Water 80%, Glycerin, Niacinamide, Adenosine",
      keyIngredients: "Ginseng Root Water 80%, Niacinamide",
      skinTypes: "dry, normal, mature",
      skinConcerns: "idratazione, anti-età, elasticità",
      price: 22.00,
      size: "150ml",
      rating: 4.7,
      reviewCount: 892,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://beautyofjoseon.com/wp-content/uploads/2022/11/Ginseng-Essence-Water-1.png",
      officialUrl: "https://beautyofjoseon.com/product/ginseng-essence-water/",
      yesStyleUrl: "https://www.yesstyle.com/it/beauty-of-joseon-ginseng-essence-water-150ml/info.html/pid.1058349565",
    },
    {
      productId: "BOJ-GINSENG-SERUM",
      name: "Revive Serum: Ginseng + Snail Mucin",
      brand: "Beauty of Joseon",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "serum",
      description: "Siero con ginseng 30% e bava di lumaca 55% per effetto anti-età rigenerante.",
      ingredients: "Snail Secretion Filtrate 55%, Panax Ginseng Root Water 30%, Niacinamide",
      keyIngredients: "Snail Mucin 55%, Ginseng 30%",
      skinTypes: "all, dry, mature",
      skinConcerns: "anti-età, rughe, elasticità",
      price: 24.00,
      size: "30ml",
      rating: 4.6,
      reviewCount: 645,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://beautyofjoseon.com/wp-content/uploads/2022/11/Revive-Serum-Ginseng-Snail-Mucin-1.png",
      officialUrl: "https://beautyofjoseon.com/product/revive-serum-ginseng-snail-mucin/",
      yesStyleUrl: "https://www.yesstyle.com/it/beauty-of-joseon-revive-serum-ginseng-snail-mucin-30ml/info.html/pid.1058349581",
    },

    // ==================== DEAR KLAIRS - K-Beauty ====================
    {
      productId: "KLAIRS-VITAMIN-DROP",
      name: "Freshly Juiced Vitamin Drop",
      brand: "Dear Klairs",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "serum",
      description: "Siero con Vitamina C 5% pura (Ascorbic Acid), ideale per pelli sensibili. Illumina e uniforma l'incarnato.",
      ingredients: "Ascorbic Acid 5%, Propylene Glycol, Vitamin E",
      keyIngredients: "Vitamin C 5%, Vitamin E",
      skinTypes: "all, sensitive",
      skinConcerns: "macchie, luminosità, anti-età",
      price: 27.00,
      size: "35ml",
      rating: 4.5,
      reviewCount: 2341,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://klairs.com/wp-content/uploads/2023/03/Freshly-Juiced-Vitamin-Drop.png",
      officialUrl: "https://klairs.com/product/freshly-juiced-vitamin-drop/",
      yesStyleUrl: "https://www.yesstyle.com/it/dear-klairs-freshly-juiced-vitamin-drop-35ml/info.html/pid.1031164896",
      amazonUrl: "https://www.amazon.it/dp/B00H2BGJYQ",
    },
    {
      productId: "KLAIRS-SUPPLE-PREPARATION-TONER",
      name: "Supple Preparation Unscented Toner",
      brand: "Dear Klairs",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Tonico viso idratante senza profumo con acido ialuronico e beta-glucano.",
      ingredients: "Water, Butylene Glycol, Glycerin, Sodium Hyaluronate, Beta-Glucan",
      keyIngredients: "Hyaluronic Acid, Beta-Glucan, Panthenol",
      skinTypes: "all, sensitive, dry",
      skinConcerns: "idratazione, sensibilità, barriera",
      price: 23.00,
      size: "180ml",
      rating: 4.8,
      reviewCount: 1892,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://klairs.com/wp-content/uploads/2023/03/Supple-Preparation-Unscented-Toner.png",
      officialUrl: "https://klairs.com/product/supple-preparation-unscented-toner/",
      yesStyleUrl: "https://www.yesstyle.com/it/dear-klairs-supple-preparation-unscented-toner-180ml/info.html/pid.1031164936",
    },

    // ==================== LANEIGE - K-Beauty ====================
    {
      productId: "LANEIGE-WATER-SLEEPING-MASK",
      name: "Water Sleeping Mask EX",
      brand: "Laneige",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "mask",
      description: "Maschera notturna idratante con tecnologia Sleep-Tox. Soffice texture gel che si assorbe rapidamente.",
      ingredients: "Water, Glycerin, Butylene Glycol, Beta-Glucan, Sleepscent",
      keyIngredients: "Beta-Glucan, Hyaluronic Acid, Sleepscent",
      skinTypes: "all",
      skinConcerns: "idratazione, luminosità, riparazione notturna",
      price: 28.00,
      size: "70ml",
      rating: 4.6,
      reviewCount: 4521,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://www.laneige.com/int/en/products/__media__/products/20231031_water_sleeping_mask_ex_70ml.png",
      officialUrl: "https://www.laneige.com/int/en/product/water-sleeping-mask.html",
      sephoraUrl: "https://www.sephora.it/p/water-sleeping-mask-P454220.html",
      amazonUrl: "https://www.amazon.it/dp/B00TQZ7HRG",
    },
    {
      productId: "LANEIGE-LIP-SLEEPING-MASK",
      name: "Lip Sleeping Mask",
      brand: "Laneige",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "lip care",
      description: "Maschera labbra notturna con Berry Mix Complex. Idrata e lenisce le labbra screpolate.",
      ingredients: "Butylene Glycol, Berry Mix Complex, Murumuru Butter, Shea Butter",
      keyIngredients: "Berry Mix Complex, Vitamin C, Murumuru Butter",
      skinTypes: "all",
      skinConcerns: "labbra screpolate, idratazione labbra",
      price: 24.00,
      size: "20g",
      rating: 4.8,
      reviewCount: 6789,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://www.laneige.com/int/en/products/__media__/products/20231101_lip_sleeping_mask_berry_20g.png",
      officialUrl: "https://www.laneige.com/int/en/product/lip-sleeping-mask.html",
      sephoraUrl: "https://www.sephora.it/p/lip-sleeping-mask-P420894.html",
      amazonUrl: "https://www.amazon.it/dp/B01N4N7D2F",
    },

    // ==================== ROUND LAB - K-Beauty ====================
    {
      productId: "ROUNDLAB-DOKDO-TONER",
      name: "Dokdo Toner",
      brand: "Round Lab",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Tonico viso con acqua profonda dell'isola di Ulleungdo 72%. Delicato e idratante.",
      ingredients: "Deep Sea Water 72%, Sodium Hyaluronate, Allantoin, Panthenol",
      keyIngredients: "Deep Sea Water 72%, Hyaluronic Acid",
      skinTypes: "sensitive, dry, normal",
      skinConcerns: "idratazione, pH, sensibilità",
      price: 16.00,
      size: "200ml",
      rating: 4.7,
      reviewCount: 923,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://global.yesstyle.com/gimg/001/001-4-5/400x400/1050016339.jpg",
      officialUrl: "https://www.roundlab.com/product/dokdo-toner/2/",
      yesStyleUrl: "https://www.yesstyle.com/it/round-lab-dokdo-toner-200ml/info.html/pid.1050016339",
    },

    // ==================== PURITO - K-Beauty ====================
    {
      productId: "PURITO-CENTELLA-BUFFET-SERUM",
      name: "Centella Green Level Buffet Serum",
      brand: "Purito",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "serum",
      description: "Siero multifunzione con Centella Asiatica 49% e peptidi. Lenisce, idrata e combatte i segni dell'invecchiamento.",
      ingredients: "Centella Asiatica Extract 49%, Niacinamide, Peptides, Hyaluronic Acid",
      keyIngredients: "Centella Asiatica 49%, Peptides, Niacinamide 2%",
      skinTypes: "sensitive, combination, dry, normal",
      skinConcerns: "idratazione, barriera, anti-età, sensibilità",
      price: 22.00,
      size: "60ml",
      rating: 4.6,
      reviewCount: 1234,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://global.yesstyle.com/gimg/001/001-4-5/400x400/1053123848.jpg",
      officialUrl: "https://www.purito.com/product/centella-green-level-buffet-serum",
      yesStyleUrl: "https://www.yesstyle.com/it/purito-centella-green-level-buffet-serum-60ml/info.html/pid.1053123848",
    },

    // ==================== ISNTREE - K-Beauty ====================
    {
      productId: "ISNTREE-HYALURONIC-ACID-TONER",
      name: "Hyaluronic Acid Toner Plus",
      brand: "Isntree",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Tonico viso con 50% di acido ialuronico per idratazione intensa.",
      ingredients: "Sodium Hyaluronate 50%, Hydrolyzed Hyaluronic Acid, Panthenol",
      keyIngredients: "Hyaluronic Acid 50%, Panthenol",
      skinTypes: "all, dry, dehydrated",
      skinConcerns: "idratazione, disidratazione, secchezza",
      price: 18.00,
      size: "200ml",
      rating: 4.7,
      reviewCount: 1234,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://global.yesstyle.com/gimg/001/001-4-5/400x400/1047642589.jpg",
      officialUrl: "https://isntree.com/product/hyaluronic-acid-toner-plus/",
      yesStyleUrl: "https://www.yesstyle.com/it/isntree-hyaluronic-acid-toner-plus-200ml/info.html/pid.1047642589",
    },

    // ==================== TORRIDEN - K-Beauty ====================
    {
      productId: "TORRIDEN-DIVE-IN-SERUM",
      name: "Dive-In Serum",
      brand: "Torriden",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "serum",
      description: "Siero idratante con acido ialuronico a basso peso molecolare.",
      ingredients: "Low Molecular Hyaluronic Acid, Panthenol, Allantoin",
      keyIngredients: "Low Molecular Hyaluronic Acid, Panthenol",
      skinTypes: "all, dry, dehydrated",
      skinConcerns: "idratazione, disidratazione",
      price: 19.00,
      size: "50ml",
      rating: 4.6,
      reviewCount: 876,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://global.yesstyle.com/gimg/001/001-4-5/400x400/1074890020.jpg",
      officialUrl: "https://torriden.com/product/dive-in-serum/",
      yesStyleUrl: "https://www.yesstyle.com/it/torriden-dive-in-serum-50ml/info.html/pid.1074890020",
    },

    // ==================== ANUA - K-Beauty ====================
    {
      productId: "ANUA-HEARTLEAF-TONER",
      name: "Heartleaf 77% Soothing Toner",
      brand: "Anua",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Tonico lenitivo con estratto di Heartleaf 77% (Houttuynia Cordata).",
      ingredients: "Houttuynia Cordata Extract 77%, Panthenol, Allantoin",
      keyIngredients: "Heartleaf Extract 77%, Panthenol",
      skinTypes: "sensitive, oily, acne-prone",
      skinConcerns: "sensibilità, acne, arrossamenti",
      price: 23.00,
      size: "250ml",
      rating: 4.7,
      reviewCount: 2341,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://global.yesstyle.com/gimg/001/001-4-5/400x400/1079352511.jpg",
      officialUrl: "https://anua.com/product/heartleaf-77-soothing-toner/",
      yesStyleUrl: "https://www.yesstyle.com/it/anua-heartleaf-77-soothing-toner-250ml/info.html/pid.1079352511",
    },

    // ==================== SOME BY MI - K-Beauty ====================
    {
      productId: "SOMEBYMI-AHA-BHA-PHA-TONER",
      name: "AHA BHA PHA 30 Days Miracle Toner",
      brand: "Some By Mi",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Tonico esfoliante con AHA, BHA, PHA per pelle con acne.",
      ingredients: "AHA, BHA, PHA, Tea Tree, Centella Asiatica",
      keyIngredients: "AHA, BHA, PHA, Tea Tree",
      skinTypes: "oily, acne-prone, combination",
      skinConcerns: "acne, punti neri, pori, texture",
      price: 22.00,
      size: "150ml",
      rating: 4.5,
      reviewCount: 2341,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://global.yesstyle.com/gimg/001/001-4-5/400x400/1062959871.jpg",
      officialUrl: "https://www.somebymi.com/product/aha-bha-pha-30-days-miracle-toner/",
      yesStyleUrl: "https://www.yesstyle.com/it/some-by-mi-aha-bha-pha-30-days-miracle-toner-150ml/info.html/pid.1062959871",
    },

    // ==================== I'M FROM - K-Beauty ====================
    {
      productId: "IMFROM-RICE-TONER",
      name: "Rice Toner",
      brand: "I'm From",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Tonico viso con estratto di riso coreano 77.78%.",
      ingredients: "Oryza Sativa Rice Extract 77.78%, Niacinamide, Hyaluronic Acid",
      keyIngredients: "Rice Extract 77.78%, Niacinamide",
      skinTypes: "all, dry, dehydrated",
      skinConcerns: "idratazione, luminosità",
      price: 25.00,
      size: "150ml",
      rating: 4.7,
      reviewCount: 1234,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://global.yesstyle.com/gimg/001/001-4-5/400x400/1062960519.jpg",
      officialUrl: "https://imfrom.com/product/rice-toner/",
      yesStyleUrl: "https://www.yesstyle.com/it/im-from-rice-toner-150ml/info.html/pid.1062960519",
    },

    // ==================== LA ROCHE-POSAY - Francia (SITO ITALIANO) ====================
    {
      productId: "LRP-CICAPLAST-BAUME-B5",
      name: "Cicaplast Baume B5+",
      brand: "La Roche-Posay",
      brandCountry: "Francia",
      category: "skincare",
      productType: "cream",
      description: "Balsamo riparatore multiuso con Panthenol 5% e Madecassoside. Ripara e protegge la pelle irritata.",
      ingredients: "Panthenol 5%, Madecassoside, Copper, Zinc, Manganese",
      keyIngredients: "Panthenol 5%, Madecassoside, Copper/Zinc/Manganese",
      skinTypes: "sensitive, dry, irritated",
      skinConcerns: "riparazione, sensibilità, arrossamenti, barriera",
      price: 16.90,
      size: "40ml",
      rating: 4.8,
      reviewCount: 8234,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://www.laroche-posay.it/-/media/project/loreal/brand-sites/lrp/europe/italy/products/cicaplast-baume-b5plus/01_lrp_cicaplast-baume-b5plus_40ml.png",
      officialUrl: "https://www.laroche-posay.it/cicaplast-baume-b5",
      amazonUrl: "https://www.amazon.it/dp/B00TQZ7HQG",
    },
    {
      productId: "LRP-EFFACLAR-DUO-PLUS",
      name: "Effaclar Duo+",
      brand: "La Roche-Posay",
      brandCountry: "Francia",
      category: "skincare",
      productType: "treatment",
      description: "Trattamento anti-imperfezioni con Niacinamide e LHA. Riduce brufoli, punti neri e macchie post-acne.",
      ingredients: "Niacinamide, LHA, Salicylic Acid, Piroctone Olamine",
      keyIngredients: "Niacinamide, LHA, Salicylic Acid",
      skinTypes: "oily, combination, acne-prone",
      skinConcerns: "acne, imperfezioni, pori, macchie",
      price: 19.90,
      size: "40ml",
      rating: 4.5,
      reviewCount: 5678,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://www.laroche-posay.it/-/media/project/loreal/brand-sites/lrp/europe/italy/products/effaclar-duo-plus/01_lrp_effaclar-duo-plus_40ml.png",
      officialUrl: "https://www.laroche-posay.it/effaclar-duo",
      amazonUrl: "https://www.amazon.it/dp/B00TQZ7HQA",
    },
    {
      productId: "LRP-ANTHELIOS-SPF50",
      name: "Anthelios UVMune 400 SPF50+",
      brand: "La Roche-Posay",
      brandCountry: "Francia",
      category: "skincare",
      productType: "spf",
      description: "Crema solare con filtro UV ultra-largo, SPF50+. Fluida e non grassa.",
      ingredients: "Mexoryl 400, La Roche-Posay Thermal Spring Water, Glycerin",
      keyIngredients: "Mexoryl 400, Thermal Spring Water",
      skinTypes: "all, sensitive",
      skinConcerns: "protezione solare, anti-età",
      price: 19.90,
      size: "50ml",
      rating: 4.7,
      reviewCount: 3456,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://www.laroche-posay.it/-/media/project/loreal/brand-sites/lrp/europe/italy/products/anthelios-uvmune/01_lrp_anthelios_uvmune_50ml.png",
      officialUrl: "https://www.laroche-posay.it/anthelios-uvmune-400",
      amazonUrl: "https://www.amazon.it/dp/B0B3JQK8HM",
    },

    // ==================== BIODERMA - Francia (SITO ITALIANO) ====================
    {
      productId: "BIODERMA-SENSIBIO-H2O",
      name: "Sensibio H2O",
      brand: "Bioderma",
      brandCountry: "Francia",
      category: "skincare",
      productType: "cleanser",
      description: "Acqua micellare delicata per pelli sensibili. Rimuove trucco e impurità senza irritare.",
      ingredients: "Cucurbita Pepo, Micellar Technology, Mannitol",
      keyIngredients: "Cucurbita Pepo, Micellar Technology",
      skinTypes: "sensitive, all",
      skinConcerns: "detersione delicata, sensibilità",
      price: 14.90,
      size: "500ml",
      rating: 4.7,
      reviewCount: 12453,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://www.bioderma.it/sites/default/files/styles/product_medium/public/2023-03/sensibio-h2o-500ml.png",
      officialUrl: "https://www.bioderma.it/sensibio-h2o",
      amazonUrl: "https://www.amazon.it/dp/B003156P8Y",
    },
    {
      productId: "BIODERMA-ATODERM-CREAM",
      name: "Atoderm Crème",
      brand: "Bioderma",
      brandCountry: "Francia",
      category: "skincare",
      productType: "cream",
      description: "Crema idratante per pelli molto secche e sensibili. Ripara la barriera cutanea.",
      ingredients: "Ceramidi, Niacinamide, Shega Science",
      keyIngredients: "Ceramidi, Niacinamide",
      skinTypes: "dry, very dry, sensitive",
      skinConcerns: "idratazione, secchezza, barriera",
      price: 16.90,
      size: "500ml",
      rating: 4.6,
      reviewCount: 5678,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://www.bioderma.it/sites/default/files/styles/product_medium/public/2023-03/atoderm-creme-500ml.png",
      officialUrl: "https://www.bioderma.it/atoderm-creme",
      amazonUrl: "https://www.amazon.it/dp/B00I7VH9GS",
    },

    // ==================== VICHY - Francia (SITO ITALIANO) ====================
    {
      productId: "VICHY-MINERAL-89",
      name: "Minéral 89 Hyaluronic Acid",
      brand: "Vichy",
      brandCountry: "Francia",
      category: "skincare",
      productType: "serum",
      description: "Booster idratante con acqua termale di Vichy 89% e acido ialuronico. Rinforza la barriera cutanea.",
      ingredients: "Vichy Volcanic Water 89%, Sodium Hyaluronate, Glycerin",
      keyIngredients: "Vichy Volcanic Water 89%, Hyaluronic Acid",
      skinTypes: "all, sensitive",
      skinConcerns: "idratazione, barriera, sensibilità",
      price: 19.90,
      size: "50ml",
      rating: 4.6,
      reviewCount: 3456,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://www.vichy.it/-/media/project/loreal/brand-sites/vichy/europe/italy/products/mineral-89/01_vichy_mineral-89_50ml.png",
      officialUrl: "https://www.vichy.it/mineral-89",
      amazonUrl: "https://www.amazon.it/dp/B079NG3W7J",
    },
    {
      productId: "VICHY-NORMADERM-PHYTO",
      name: "Normaderm Phytosolution",
      brand: "Vichy",
      brandCountry: "Francia",
      category: "skincare",
      productType: "treatment",
      description: "Trattamento correttivo per pelli con imperfezioni con acido salicilico e probiotici.",
      ingredients: "Salicylic Acid, Probiotics, Zinc, Vichy Thermal Water",
      keyIngredients: "Salicylic Acid, Probiotics, Zinc",
      skinTypes: "oily, acne-prone",
      skinConcerns: "acne, imperfezioni, pori",
      price: 18.90,
      size: "50ml",
      rating: 4.4,
      reviewCount: 2345,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://www.vichy.it/-/media/project/loreal/brand-sites/vichy/europe/italy/products/normaderm/01_vichy_normaderm_50ml.png",
      officialUrl: "https://www.vichy.it/normaderm-phytosolution",
      amazonUrl: "https://www.amazon.it/dp/B00TQZ7HVA",
    },

    // ==================== THE ORDINARY - Canada ====================
    {
      productId: "ORD-NIACINAMIDE-10-ZINC-1",
      name: "Niacinamide 10% + Zinc 1%",
      brand: "The Ordinary",
      brandCountry: "Canada",
      category: "skincare",
      productType: "serum",
      description: "Siero con Niacinamide 10% e Zinc 1% per ridurre pori e imperfezioni.",
      ingredients: "Niacinamide 10%, Zinc PCA 1%, Pentylene Glycol",
      keyIngredients: "Niacinamide 10%, Zinc 1%",
      skinTypes: "oily, combination",
      skinConcerns: "pori, sebo, acne, imperfezioni",
      price: 6.90,
      size: "30ml",
      rating: 4.5,
      reviewCount: 8934,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw3f2e4a4f/Images/products/The%20Ordinary/rdn-niacinamide-10pct-zinc-1pct-30ml.png?sw=600&sh=600&sm=fit",
      officialUrl: "https://theordinary.com/it-it/products/niacinamide-10pct-zinc-1pct",
      sephoraUrl: "https://www.sephora.it/p/niacinamide-10-zinc-1-P454366.html",
      amazonUrl: "https://www.amazon.it/dp/B06XKXVQZS",
    },
    {
      productId: "ORD-RETINOL-05-SQUALANE",
      name: "Retinol 0.5% in Squalane",
      brand: "The Ordinary",
      brandCountry: "Canada",
      category: "skincare",
      productType: "treatment",
      description: "Trattamento anti-età con Retinolo 0.5% in olio di squalano.",
      ingredients: "Retinol 0.5%, Squalane, Caprylic/Capric Triglyceride",
      keyIngredients: "Retinol 0.5%, Squalane",
      skinTypes: "normal, combination, dry",
      skinConcerns: "anti-età, rughe, texture",
      price: 8.90,
      size: "30ml",
      rating: 4.4,
      reviewCount: 5678,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw2e3daaf3/Images/products/The%20Ordinary/rdn-retinol-0-5pct-in-squalane-30ml.png?sw=600&sh=600&sm=fit",
      officialUrl: "https://theordinary.com/it-it/products/retinol-0-5-in-squalane",
      amazonUrl: "https://www.amazon.it/dp/B079NGH2JT",
    },
    {
      productId: "ORD-HYALURONIC-ACID-2-B5",
      name: "Hyaluronic Acid 2% + B5",
      brand: "The Ordinary",
      brandCountry: "Canada",
      category: "skincare",
      productType: "serum",
      description: "Siero idratante con acido ialuronico multi-peso molecolare 2% e Vitamina B5.",
      ingredients: "Sodium Hyaluronate Crosspolymer 2%, Panthenol 1%",
      keyIngredients: "Hyaluronic Acid 2%, Vitamin B5",
      skinTypes: "all, dehydrated",
      skinConcerns: "idratazione, disidratazione",
      price: 7.90,
      size: "30ml",
      rating: 4.5,
      reviewCount: 6789,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw4e0c4b18/Images/products/The%20Ordinary/rdn-hyaluronic-acid-2pct-b5-30ml.png?sw=600&sh=600&sm=fit",
      officialUrl: "https://theordinary.com/it-it/products/hyaluronic-acid-2-b5",
      amazonUrl: "https://www.amazon.it/dp/B06XKXVQP2",
    },
    {
      productId: "ORD-ALPHA-ARBUTIN-2-HA",
      name: "Alpha Arbutin 2% + HA",
      brand: "The Ordinary",
      brandCountry: "Canada",
      category: "skincare",
      productType: "serum",
      description: "Siero schiarente con Alpha-Arbutin 2% per ridurre macchie e iperpigmentazione.",
      ingredients: "Alpha-Arbutin 2%, Hyaluronic Acid",
      keyIngredients: "Alpha-Arbutin 2%, Hyaluronic Acid",
      skinTypes: "all",
      skinConcerns: "macchie, iperpigmentazione, uniformità",
      price: 9.90,
      size: "30ml",
      rating: 4.4,
      reviewCount: 3456,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw5f5e5f5e/Images/products/The%20Ordinary/rdn-alpha-arbutin-2pct-ha-30ml.png?sw=600&sh=600&sm=fit",
      officialUrl: "https://theordinary.com/it-it/products/alpha-arbutin-2pct-ha",
      amazonUrl: "https://www.amazon.it/dp/B06XKXVQQF",
    },

    // ==================== CERAVE - USA ====================
    {
      productId: "CERAVE-HYDRATING-CLEANSER",
      name: "Hydrating Facial Cleanser",
      brand: "CeraVe",
      brandCountry: "USA",
      category: "skincare",
      productType: "cleanser",
      description: "Detergente idratante con ceramidi e acido ialuronico. Non schiumogeno.",
      ingredients: "Ceramide NP, Ceramide AP, Ceramide EOP, Hyaluronic Acid",
      keyIngredients: "Ceramides 1, 3, 6-II, Hyaluronic Acid",
      skinTypes: "dry, sensitive, normal",
      skinConcerns: "idratazione, barriera, sensibilità, detersione",
      price: 14.00,
      size: "236ml",
      rating: 4.7,
      reviewCount: 12453,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://www.cerave.com/-/media/cerave/products/473/25297_cerave_hydrating_facial_cleanser_normal_to_dry_skin_12_floz_355ml_front_rgb.png",
      officialUrl: "https://www.cerave.com/hydrating-facial-cleanser",
      amazonUrl: "https://www.amazon.it/dp/B00I7VH9GS",
    },
    {
      productId: "CERAVE-MOISTURIZING-CREAM",
      name: "Moisturizing Cream",
      brand: "CeraVe",
      brandCountry: "USA",
      category: "skincare",
      productType: "cream",
      description: "Crema idratante con ceramidi e acido ialuronico. Formula ricca per pelli molto secche.",
      ingredients: "Ceramide NP, Ceramide AP, Ceramide EOP, Hyaluronic Acid, Petrolatum",
      keyIngredients: "Ceramides, Hyaluronic Acid, Petrolatum",
      skinTypes: "dry, very dry, normal, sensitive",
      skinConcerns: "idratazione, barriera, secchezza",
      price: 18.00,
      size: "453g",
      rating: 4.8,
      reviewCount: 15678,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://www.cerave.com/-/media/cerave/products/473/25200_cerave_moisturizing_cream_16_oz_453g_front_rgb.png",
      officialUrl: "https://www.cerave.com/moisturizing-cream",
      amazonUrl: "https://www.amazon.it/dp/B001VBSBSG",
    },

    // ==================== PAULA'S CHOICE - USA ====================
    {
      productId: "PC-BHA-2-LIQUID",
      name: "Skin Perfecting 2% BHA Liquid Exfoliant",
      brand: "Paulas Choice",
      brandCountry: "USA",
      category: "skincare",
      productType: "exfoliant",
      description: "Esfoliante liquido con acido salicilico 2%. Illumina la pelle, riduce pori e punti neri.",
      ingredients: "Salicylic Acid 2%, Green Tea Extract, Butylene Glycol",
      keyIngredients: "Salicylic Acid 2%, Green Tea Extract",
      skinTypes: "oily, combination, acne-prone",
      skinConcerns: "pori, acne, texture, punti neri",
      price: 35.00,
      size: "118ml",
      rating: 4.7,
      reviewCount: 6789,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://www.paulaschoice.com/dw/image/v2/BBSK_PRD/on/demandware.static/-/Sites-paulas-choice-master-catalog/default/dw45e10cd7/images/products/face-exfoliants/201-MINI.png?sw=600&sh=600&sm=fit",
      officialUrl: "https://www.paulaschoice.com/skin-perfecting-2pct-bha-liquid-exfoliant",
      sephoraUrl: "https://www.sephora.it/p/skin-perfecting-2-bha-liquid-exfoliant-P454376.html",
      amazonUrl: "https://www.amazon.it/dp/B00NTTHTXO",
    },

    // ==================== HADA LABO - Giappone ====================
    {
      productId: "HADALABO-GOKUJYUN-PREMIUM",
      name: "Gokujyun Premium Hyaluronic Acid Lotion",
      brand: "Hada Labo",
      brandCountry: "Giappone",
      category: "skincare",
      productType: "toner",
      description: "Lozione con 7 tipi di acido ialuronico. Idratazione profonda per tutti gli strati della pelle.",
      ingredients: "Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Sodium Acetylated Hyaluronate",
      keyIngredients: "7 Types of Hyaluronic Acid",
      skinTypes: "all, dry, dehydrated",
      skinConcerns: "idratazione, disidratazione",
      price: 15.00,
      size: "170ml",
      rating: 4.8,
      reviewCount: 5678,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: false,
      imageUrl: "https://hadalabo.us/cdn/shop/products/Gokujyun_Premium_Hyaluronic_Acid_Lotion_170ml.png?v=1678870844&width=600",
      officialUrl: "https://hadalabo.us/products/gokujyun-premium-hyaluronic-acid-lotion",
      yesStyleUrl: "https://www.yesstyle.com/it/hada-labo-gokujyun-premium-hyaluronic-acid-lotion-170ml/info.html/pid.1055304750",
      amazonUrl: "https://www.amazon.it/dp/B07V5QT1LJ",
    },

    // ==================== OLAPLEX - USA ====================
    {
      productId: "OLAPLEX-NO3",
      name: "No.3 Hair Perfector",
      brand: "Olaplex",
      brandCountry: "USA",
      category: "haircare",
      productType: "treatment",
      description: "Trattamento riparatore professionale per capelli danneggiati.",
      ingredients: "Bis-Aminopropyl Diglycol Dimaleate, Propylene Glycol",
      keyIngredients: "Bis-Aminopropyl Diglycol Dimaleate",
      hairTypes: "damaged, colored, treated",
      hairConcerns: "danni, rottura, trattamenti chimici",
      price: 32.00,
      size: "100ml",
      rating: 4.8,
      reviewCount: 8976,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://www.olaplex.com/cdn/shop/products/Olaplex_No3_Hair_Perfector_100ml.png?v=1678870844&width=600",
      officialUrl: "https://www.olaplex.com/products/no-3-hair-perfector",
      sephoraUrl: "https://www.sephora.it/p/olaplex-hair-perfector-no-3-P454227.html",
      amazonUrl: "https://www.amazon.it/dp/B00TQZ7HTS",
    },

    // ==================== SK-II - Giappone ====================
    {
      productId: "SKII-FTE",
      name: "Facial Treatment Essence",
      brand: "SK-II",
      brandCountry: "Giappone",
      category: "skincare",
      productType: "essence",
      description: "Essenza leggendaria con PITERA 90%. Illumina, idrata e migliora la texture cutanea.",
      ingredients: "Galactomyces Ferment Filtrate 90%, Butylene Glycol",
      keyIngredients: "PITERA 90%, Galactomyces Ferment Filtrate",
      skinTypes: "all",
      skinConcerns: "luminosità, texture, anti-età",
      price: 99.00,
      size: "75ml",
      rating: 4.7,
      reviewCount: 3456,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://www.sk-ii.com/-/media/project/loreal/brand-sites/sk-ii/global/products/fte/01_sk-ii_facial_treatment_essence_75ml.png",
      officialUrl: "https://www.sk-ii.com/facial-treatment-essence",
      sephoraUrl: "https://www.sephora.it/p/sk-ii-facial-treatment-essence-P454247.html",
    },

    // ==================== ESTÉE LAUDER - USA ====================
    {
      productId: "ESTEE-ANR",
      name: "Advanced Night Repair Serum",
      brand: "Estee Lauder",
      brandCountry: "USA",
      category: "skincare",
      productType: "serum",
      description: "Siero notturno riparatore con tecnologia ChronoluxCB. Riduce rughe e migliora l'elasticità.",
      ingredients: "Bifida Ferment Lysate, Tripeptide-32, Sodium Hyaluronate",
      keyIngredients: "ChronoluxCB, Bifida Ferment Lysate",
      skinTypes: "all",
      skinConcerns: "anti-età, riparazione, rughe",
      price: 89.00,
      size: "30ml",
      rating: 4.8,
      reviewCount: 5678,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://www.esteelauder.com/-/media/project/loreal/brand-sites/estee-luder/global/products/anr/01_estee_lauder_advanced_night_repair_30ml.png",
      officialUrl: "https://www.esteelauder.com/advanced-night-repair",
      sephoraUrl: "https://www.sephora.it/p/estee-lauder-advanced-night-repair-P454257.html",
    },

    // ==================== DRUNK ELEPHANT - USA ====================
    {
      productId: "DRUNK-PROTINI",
      name: "Protini Polypeptide Cream",
      brand: "Drunk Elephant",
      brandCountry: "USA",
      category: "skincare",
      productType: "cream",
      description: "Crema viso con peptidi e acido ialuronico. Texture gel-crema leggera ma idratante.",
      ingredients: "Pygmy Waterlily, Peptides, Sodium Hyaluronate",
      keyIngredients: "Peptides, Hyaluronic Acid, Pygmy Waterlily",
      skinTypes: "all",
      skinConcerns: "anti-età, elasticità, idratazione",
      price: 68.00,
      size: "50ml",
      rating: 4.5,
      reviewCount: 3456,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://drunkelephant.com/cdn/shop/products/Protini_Polypeptide_Cream_50ml.png?v=1678870844&width=600",
      officialUrl: "https://drunkelephant.com/products/protini-polypeptide-cream",
      sephoraUrl: "https://www.sephora.it/p/drunk-elephant-protini-polypeptide-cream-P454267.html",
    },

    // ==================== L'ERBOLARIO - Italia ====================
    {
      productId: "LERBOLARIO-MANDORLA-CREAM",
      name: "Crema Mandorla",
      brand: "L'Erbolario",
      brandCountry: "Italia",
      category: "skincare",
      productType: "cream",
      description: "Crema idratante con olio di mandorle dolci e vitamina E. Delicata e nutriente.",
      ingredients: "Sweet Almond Oil, Vitamin E, Shea Butter",
      keyIngredients: "Sweet Almond Oil, Vitamin E",
      skinTypes: "dry, normal, sensitive",
      skinConcerns: "idratazione, nutrizione, delicatezza",
      price: 24.00,
      size: "250ml",
      rating: 4.6,
      reviewCount: 1234,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://www.lerbolario.com/media/catalog/product/c/r/crema_mandorla_250ml.png",
      officialUrl: "https://www.lerbolario.com/crema-mandorla",
      amazonUrl: "https://www.amazon.it/dp/B00TQZ7HXW",
    },
  ];
