export interface Product {
  productId: string;
  name: string;
  brand: string;
  brandCountry: string;
  category: string;
  productType: string;
  description: string;
  ingredients: string;
  keyIngredients: string;
  skinTypes?: string;
  skinConcerns?: string;
  hairTypes?: string;
  hairConcerns?: string;
  price: number;
  size: string;
  rating: number;
  reviewCount: number;
  isKorean: boolean;
  isVegan: boolean;
  isCrueltyFree: boolean;
  imageUrl: string;
  officialUrl: string;
  amazonUrl?: string;
  sephoraUrl?: string;
  miinUrl?: string;
}

export const products: Product[] = [
    // ==================== COSRX - K-Beauty ====================
    {
      productId: "COSRX-SNAIL-96-ESSENCE",
      name: "Advanced Snail 96 Mucin Power Essence",
      brand: "COSRX",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "essence",
      description: "Essenza concentrata al 96% di bava di lumaca per idratazione intensa e riparazione cutanea. Formulata con Snail Secretion Filtrate per una pelle più luminosa ed elastica.",
      ingredients: "Snail Secretion Filtrate, Betaine, Butylene Glycol, Sodium Hyaluronate, Panthenol, Allantoin, Arginine",
      keyIngredients: "Snail Mucin 96%, Hyaluronic Acid, Panthenol",
      skinTypes: "all, dry, sensitive, normal, combination",
      skinConcerns: "idratazione, anti-età, cicatrizzazione, arrossamenti, barriera cutanea",
      price: 25.90,
      size: "100ml",
      rating: 4.8,
      reviewCount: 2847,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.com/6042-product_zoom/advanced-snail-96-mucin-power-essence.jpg",
      officialUrl: "https://cosrx.com/products/advanced-snail-96-mucin-power-essence",
      miinUrl: "https://miin-cosmetics.com/advanced-snail-96-mucin-power-essence/63",
      amazonUrl: "https://www.amazon.it/dp/B00PBSZ9M0",
    },
    {
      productId: "COSRX-LOW-PH-CLEANSER",
      name: "Low pH Good Morning Gel Cleanser",
      brand: "COSRX",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "cleanser",
      description: "Detergente viso gel con pH 5.5, delicato ma efficace con BHA e tea tree oil. Perfetto per pelli sensibili e a tendenza acneica.",
      ingredients: "Water, Cocamidopropyl Betaine, Glycerin, Tea Tree Leaf Oil, Betaine Salicylate",
      keyIngredients: "Tea Tree Oil, BHA 0.5%, Betaine",
      skinTypes: "sensitive, oily, combination, acne-prone",
      skinConcerns: "detersione, pH equilibrato, acne, pelle grassa",
      price: 12.50,
      size: "150ml",
      rating: 4.6,
      reviewCount: 3421,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.com/6059-product_zoom/low-ph-good-morning-gel-cleanser.jpg",
      officialUrl: "https://cosrx.com/products/low-ph-good-morning-gel-cleanser",
      miinUrl: "https://miin-cosmetics.com/low-ph-good-morning-gel-cleanser/71",
      amazonUrl: "https://www.amazon.it/dp/B01M0GB8CC",
    },
    {
      productId: "COSRX-AHA7-WHITEHEAD",
      name: "AHA 7 Whitehead Power Liquid",
      brand: "COSRX",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "exfoliant",
      description: "Esfoliante chimico con acido glicolico 7% per eliminare le cellule morte e migliorare la texture cutanea.",
      ingredients: "Water, Glycolic Acid, Butylene Glycol, Niacinamide",
      keyIngredients: "Glycolic Acid 7%, Niacinamide",
      skinTypes: "normal, combination, oily",
      skinConcerns: "texture, macchie, pori, punti bianchi",
      price: 25.00,
      size: "100ml",
      rating: 4.6,
      reviewCount: 2134,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.com/6044-product_zoom/aha-7-whitehead-power-liquid.jpg",
      officialUrl: "https://cosrx.com/products/aha-7-whitehead-power-liquid",
      miinUrl: "https://miin-cosmetics.com/aha-7-whitehead-power-liquid/566",
    },
    {
      productId: "COSRX-BHA-BLACKHEAD",
      name: "BHA Blackhead Power Liquid",
      brand: "COSRX",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "exfoliant",
      description: "Trattamento con acido salicilico 4% per punti neri e pori dilatati. Penetra nei pori per eliminare sebo e impurità.",
      ingredients: "Water, Betaine Salicylate, Butylene Glycol, Tea Tree Extract",
      keyIngredients: "Salicylic Acid 4%, Tea Tree Extract",
      skinTypes: "oily, combination, acne-prone",
      skinConcerns: "punti neri, pori, acne, sebo",
      price: 26.00,
      size: "100ml",
      rating: 4.5,
      reviewCount: 1892,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.com/6048-product_zoom/bha-blackhead-power-liquid.jpg",
      officialUrl: "https://cosrx.com/products/bha-blackhead-power-liquid",
      miinUrl: "https://miin-cosmetics.com/bha-blackhead-power-liquid/66",
    },

    // ==================== BEAUTY OF JOSEON - K-Beauty ====================
    {
      productId: "BOJ-RELIEF-SUN-SPF50",
      name: "Relief Sun: Rice + Probiotics SPF50+ PA++++",
      brand: "Beauty of Joseon",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "spf",
      description: "Crema solare leggera con estratto di riso 30% e probiotici, SPF50+ PA++++. Texture non appiccicosa, ideale come base trucco.",
      ingredients: "Water, Propanediol, Homosalate, Niacinamide, Rice Extract 30%",
      keyIngredients: "Rice Extract 30%, Niacinamide 2%, Probiotics",
      skinTypes: "all",
      skinConcerns: "protezione solare, anti-età, idratazione",
      price: 18.90,
      size: "50ml",
      rating: 4.9,
      reviewCount: 1567,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.com/10548-product_zoom/relief-sun-rice-probiotics-spf50-pa.jpg",
      officialUrl: "https://beautyofjoseon.com/product/relief-sun-rice-probiotics/",
      miinUrl: "https://miin-cosmetics.com/relief-sun-rice-probiotics-spf50-pa/1286",
      amazonUrl: "https://www.amazon.it/dp/B09V1NKL7C",
    },
    {
      productId: "BOJ-GINSENG-ESSENCE",
      name: "Ginseng Essence Water",
      brand: "Beauty of Joseon",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Essenza tonificante con 80% estratto di ginseng rosso coreano. Antiossidante e idratante.",
      ingredients: "Panax Ginseng Root Water 80%, Glycerin, Niacinamide, Adenosine",
      keyIngredients: "Ginseng Root Water 80%, Niacinamide",
      skinTypes: "dry, normal, mature",
      skinConcerns: "idratazione, anti-età, elasticità",
      price: 22.00,
      size: "150ml",
      rating: 4.7,
      reviewCount: 892,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.com/10532-product_zoom/ginseng-essence-water.jpg",
      officialUrl: "https://beautyofjoseon.com/product/ginseng-essence-water/",
      miinUrl: "https://miin-cosmetics.com/ginseng-essence-water/1282",
    },
    {
      productId: "BOJ-GINSENG-SERUM",
      name: "Revive Serum: Ginseng + Snail Mucin",
      brand: "Beauty of Joseon",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "serum",
      description: "Siero con ginseng 30% e bava di lumaca 55% per effetto anti-età rigenerante.",
      ingredients: "Snail Secretion Filtrate 55%, Panax Ginseng Root Water 30%, Niacinamide",
      keyIngredients: "Snail Mucin 55%, Ginseng 30%",
      skinTypes: "all, dry, mature",
      skinConcerns: "anti-età, rughe, elasticità",
      price: 24.00,
      size: "30ml",
      rating: 4.6,
      reviewCount: 645,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.com/10555-product_zoom/revive-serum-ginseng-snail-mucin.jpg",
      officialUrl: "https://beautyofjoseon.com/product/revive-serum-ginseng-snail-mucin/",
      miinUrl: "https://miin-cosmetics.com/revive-serum-ginseng-snail-mucin/1283",
    },

    // ==================== DEAR KLAIRS - K-Beauty ====================
    {
      productId: "KLAIRS-VITAMIN-DROP",
      name: "Freshly Juiced Vitamin Drop",
      brand: "Dear Klairs",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "serum",
      description: "Siero con Vitamina C 5% pura (Ascorbic Acid), ideale per pelli sensibili. Illumina e uniforma l'incarnato.",
      ingredients: "Ascorbic Acid 5%, Propylene Glycol, Vitamin E",
      keyIngredients: "Vitamin C 5%, Vitamin E",
      skinTypes: "all, sensitive",
      skinConcerns: "macchie, luminosità, anti-età",
      price: 27.00,
      size: "35ml",
      rating: 4.5,
      reviewCount: 2341,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.com/8941-product_zoom/freshly-juiced-vitamin-drop.jpg",
      officialUrl: "https://klairs.com/product/freshly-juiced-vitamin-drop/",
      miinUrl: "https://miin-cosmetics.com/freshly-juiced-vitamin-drop/83",
      amazonUrl: "https://www.amazon.it/dp/B00H2BGJYQ",
    },
    {
      productId: "KLAIRS-SUPPLE-PREPARATION-TONER",
      name: "Supple Preparation Unscented Toner",
      brand: "Dear Klairs",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Tonico viso idratante senza profumo con acido ialuronico e beta-glucano.",
      ingredients: "Water, Butylene Glycol, Glycerin, Sodium Hyaluronate, Beta-Glucan",
      keyIngredients: "Hyaluronic Acid, Beta-Glucan, Panthenol",
      skinTypes: "all, sensitive, dry",
      skinConcerns: "idratazione, sensibilità, barriera",
      price: 23.00,
      size: "180ml",
      rating: 4.8,
      reviewCount: 1892,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.com/9043-product_zoom/supple-preparation-unscented-facial-toner.jpg",
      officialUrl: "https://klairs.com/product/supple-preparation-unscented-toner/",
      miinUrl: "https://miin-cosmetics.com/supple-preparation-unscented-facial-toner/350",
    },

    // ==================== LANEIGE - K-Beauty ====================
    {
      productId: "LANEIGE-WATER-SLEEPING-MASK",
      name: "Water Sleeping Mask EX",
      brand: "Laneige",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "mask",
      description: "Maschera notturna idratante con tecnologia Sleep-Tox. Soffice texture gel che si assorbe rapidamente.",
      ingredients: "Water, Glycerin, Butylene Glycol, Beta-Glucan, Sleepscent",
      keyIngredients: "Beta-Glucan, Hyaluronic Acid, Sleepscent",
      skinTypes: "all",
      skinConcerns: "idratazione, luminosità, riparazione notturna",
      price: 28.00,
      size: "70ml",
      rating: 4.6,
      reviewCount: 4521,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop",
      officialUrl: "https://www.laneige.com/int/en/product/water-sleeping-mask.html",
      sephoraUrl: "https://www.sephora.it/p/water-sleeping-mask-P454220.html",
      amazonUrl: "https://www.amazon.it/dp/B00TQZ7HRG",
    },
    {
      productId: "LANEIGE-LIP-SLEEPING-MASK",
      name: "Lip Sleeping Mask",
      brand: "Laneige",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "lip care",
      description: "Maschera labbra notturna con Berry Mix Complex. Idrata e lenisce le labbra screpolate.",
      ingredients: "Butylene Glycol, Berry Mix Complex, Murumuru Butter, Shea Butter",
      keyIngredients: "Berry Mix Complex, Vitamin C, Murumuru Butter",
      skinTypes: "all",
      skinConcerns: "labbra screpolate, idratazione labbra",
      price: 24.00,
      size: "20g",
      rating: 4.8,
      reviewCount: 6789,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop",
      officialUrl: "https://www.laneige.com/int/en/product/lip-sleeping-mask.html",
      sephoraUrl: "https://www.sephora.it/p/lip-sleeping-mask-P420894.html",
      amazonUrl: "https://www.amazon.it/dp/B01N4N7D2F",
    },

    // ==================== ROUND LAB - K-Beauty ====================
    {
      productId: "ROUNDLAB-BIRCH-TONER",
      name: "Birch Juice Moisturizing Toner",
      brand: "Round Lab",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Tonico idratante con linfa di betulla 73%. Idratazione profonda e lenitiva per pelli sensibili e disidratate.",
      ingredients: "Betula Platyphylla Japonica Juice 73%, Butylene Glycol, Glycerin, Panthenol, Sodium Hyaluronate",
      keyIngredients: "Birch Sap 73%, Panthenol, Hyaluronic Acid",
      skinTypes: "sensitive, dry, normal, dehydrated",
      skinConcerns: "idratazione, sensibilità, disidratazione",
      price: 25.00,
      size: "200ml",
      rating: 4.6,
      reviewCount: 1567,
      isKorean: true,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.com/6663-product_zoom/birch-juice-moisturizing-toner.jpg",
      officialUrl: "https://roundlab.com/en/product/birch-juice-moisturizing-toner/",
      miinUrl: "https://miin-cosmetics.com/birch-juice-moisturizing-toner/1360",
    },

    // ==================== PURITO - K-Beauty ====================
    {
      productId: "PURITO-CENTELLA-BUFFET-SERUM",
      name: "Centella Green Level Buffet Serum",
      brand: "Purito",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "serum",
      description: "Siero multifunzione con Centella Asiatica 49% e peptidi. Lenisce, idrata e combatte i segni dell'invecchiamento.",
      ingredients: "Centella Asiatica Extract 49%, Niacinamide, Peptides, Hyaluronic Acid",
      keyIngredients: "Centella Asiatica 49%, Peptides, Niacinamide 2%",
      skinTypes: "sensitive, combination, dry, normal",
      skinConcerns: "idratazione, barriera, anti-età, sensibilità",
      price: 22.00,
      size: "60ml",
      rating: 4.6,
      reviewCount: 1234,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.com/11413-product_zoom/wonder-releaf-centella-serum-unscented.jpg",
      officialUrl: "https://www.purito.com/product/centella-green-level-buffet-serum",
      miinUrl: "https://miin-cosmetics.com/2060-wonder-releaf-centella-serum-unscented.html",
    },

    // ==================== ISNTREE - K-Beauty ====================
    {
      productId: "ISNTREE-HYALURONIC-ACID-TONER",
      name: "Hyaluronic Acid Toner Plus",
      brand: "Isntree",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Tonico viso con 50% di acido ialuronico per idratazione intensa.",
      ingredients: "Sodium Hyaluronate 50%, Hydrolyzed Hyaluronic Acid, Panthenol",
      keyIngredients: "Hyaluronic Acid 50%, Panthenol",
      skinTypes: "all, dry, dehydrated",
      skinConcerns: "idratazione, disidratazione, secchezza",
      price: 18.00,
      size: "200ml",
      rating: 4.7,
      reviewCount: 1234,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop",
      officialUrl: "https://isntree.com/product/hyaluronic-acid-toner-plus/",
    },

    // ==================== TORRIDEN - K-Beauty ====================
    {
      productId: "TORRIDEN-DIVE-IN-SERUM",
      name: "Dive-In Serum",
      brand: "Torriden",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "serum",
      description: "Siero idratante con acido ialuronico a basso peso molecolare.",
      ingredients: "Low Molecular Hyaluronic Acid, Panthenol, Allantoin",
      keyIngredients: "Low Molecular Hyaluronic Acid, Panthenol",
      skinTypes: "all, dry, dehydrated",
      skinConcerns: "idratazione, disidratazione",
      price: 19.00,
      size: "50ml",
      rating: 4.6,
      reviewCount: 876,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.com/10775-product_zoom/low-molecular-hyaluronic-acid-serum.jpg",
      officialUrl: "https://torriden.com/product/dive-in-serum/",
      miinUrl: "https://miin-cosmetics.com/1884-low-molecular-hyaluronic-acid-serum.html",
    },

    // ==================== ANUA - K-Beauty ====================
    {
      productId: "ANUA-HEARTLEAF-TONER",
      name: "Heartleaf 77% Soothing Toner",
      brand: "Anua",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Tonico lenitivo con estratto di Heartleaf 77% (Houttuynia Cordata).",
      ingredients: "Houttuynia Cordata Extract 77%, Panthenol, Allantoin",
      keyIngredients: "Heartleaf Extract 77%, Panthenol",
      skinTypes: "sensitive, oily, acne-prone",
      skinConcerns: "sensibilità, acne, arrossamenti",
      price: 23.00,
      size: "250ml",
      rating: 4.7,
      reviewCount: 2341,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.com/11340-product_zoom/heartleaf-77-soothing-toner.jpg",
      officialUrl: "https://anua.com/product/heartleaf-77-soothing-toner/",
      miinUrl: "https://miin-cosmetics.com/heartleaf-77-soothing-toner/1359",
    },

    // ==================== SOME BY MI - K-Beauty ====================
    {
      productId: "SOMEBYMI-AHA-BHA-PHA-TONER",
      name: "AHA BHA PHA 30 Days Miracle Toner",
      brand: "Some By Mi",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Tonico esfoliante con AHA, BHA, PHA per pelle con acne.",
      ingredients: "AHA, BHA, PHA, Tea Tree, Centella Asiatica",
      keyIngredients: "AHA, BHA, PHA, Tea Tree",
      skinTypes: "oily, acne-prone, combination",
      skinConcerns: "acne, punti neri, pori, texture",
      price: 22.00,
      size: "150ml",
      rating: 4.5,
      reviewCount: 2341,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop",
      officialUrl: "https://www.somebymi.com/product/aha-bha-pha-30-days-miracle-toner/",
    },

    // ==================== I'M FROM - K-Beauty ====================
    {
      productId: "IMFROM-RICE-TONER",
      name: "Rice Toner",
      brand: "I'm From",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Tonico viso con estratto di riso coreano 77.78%.",
      ingredients: "Oryza Sativa Rice Extract 77.78%, Niacinamide, Hyaluronic Acid",
      keyIngredients: "Rice Extract 77.78%, Niacinamide",
      skinTypes: "all, dry, dehydrated",
      skinConcerns: "idratazione, luminosità",
      price: 25.00,
      size: "150ml",
      rating: 4.7,
      reviewCount: 1234,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.com/8926-product_zoom/rice-toner.jpg",
      officialUrl: "https://imfrom.com/product/rice-toner/",
      miinUrl: "https://miin-cosmetics.com/rice-toner/1948",
    },

    // ==================== LA ROCHE-POSAY - Francia (SITO ITALIANO) ====================
    {
      productId: "LRP-CICAPLAST-BAUME-B5",
      name: "Cicaplast Baume B5+",
      brand: "La Roche-Posay",
      brandCountry: "Francia",
      category: "skincare",
      productType: "cream",
      description: "Balsamo riparatore multiuso con Panthenol 5% e Madecassoside. Ripara e protegge la pelle irritata.",
      ingredients: "Panthenol 5%, Madecassoside, Copper, Zinc, Manganese",
      keyIngredients: "Panthenol 5%, Madecassoside, Copper/Zinc/Manganese",
      skinTypes: "sensitive, dry, irritated",
      skinConcerns: "riparazione, sensibilità, arrossamenti, barriera",
      price: 16.90,
      size: "40ml",
      rating: 4.8,
      reviewCount: 8234,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://images.unsplash.com/photo-1570194065650-d99fb4b38c34?w=400&h=400&fit=crop",
      officialUrl: "https://www.laroche-posay.it/cicaplast-baume-b5",
      amazonUrl: "https://www.amazon.it/dp/B00TQZ7HQG",
    },
    {
      productId: "LRP-EFFACLAR-DUO-PLUS",
      name: "Effaclar Duo+",
      brand: "La Roche-Posay",
      brandCountry: "Francia",
      category: "skincare",
      productType: "treatment",
      description: "Trattamento anti-imperfezioni con Niacinamide e LHA. Riduce brufoli, punti neri e macchie post-acne.",
      ingredients: "Niacinamide, LHA, Salicylic Acid, Piroctone Olamine",
      keyIngredients: "Niacinamide, LHA, Salicylic Acid",
      skinTypes: "oily, combination, acne-prone",
      skinConcerns: "acne, imperfezioni, pori, macchie",
      price: 19.90,
      size: "40ml",
      rating: 4.5,
      reviewCount: 5678,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop",
      officialUrl: "https://www.laroche-posay.it/effaclar-duo",
      amazonUrl: "https://www.amazon.it/dp/B00TQZ7HQA",
    },
    {
      productId: "LRP-ANTHELIOS-SPF50",
      name: "Anthelios UVMune 400 SPF50+",
      brand: "La Roche-Posay",
      brandCountry: "Francia",
      category: "skincare",
      productType: "spf",
      description: "Crema solare con filtro UV ultra-largo, SPF50+. Fluida e non grassa.",
      ingredients: "Mexoryl 400, La Roche-Posay Thermal Spring Water, Glycerin",
      keyIngredients: "Mexoryl 400, Thermal Spring Water",
      skinTypes: "all, sensitive",
      skinConcerns: "protezione solare, anti-età",
      price: 19.90,
      size: "50ml",
      rating: 4.7,
      reviewCount: 3456,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400&h=400&fit=crop",
      officialUrl: "https://www.laroche-posay.it/anthelios-uvmune-400",
      amazonUrl: "https://www.amazon.it/dp/B0B3JQK8HM",
    },

    // ==================== BIODERMA - Francia (SITO ITALIANO) ====================
    {
      productId: "BIODERMA-SENSIBIO-H2O",
      name: "Sensibio H2O",
      brand: "Bioderma",
      brandCountry: "Francia",
      category: "skincare",
      productType: "cleanser",
      description: "Acqua micellare delicata per pelli sensibili. Rimuove trucco e impurità senza irritare.",
      ingredients: "Cucurbita Pepo, Micellar Technology, Mannitol",
      keyIngredients: "Cucurbita Pepo, Micellar Technology",
      skinTypes: "sensitive, all",
      skinConcerns: "detersione delicata, sensibilità",
      price: 14.90,
      size: "500ml",
      rating: 4.7,
      reviewCount: 12453,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop",
      officialUrl: "https://www.bioderma.it/sensibio-h2o",
      amazonUrl: "https://www.amazon.it/dp/B003156P8Y",
    },
    {
      productId: "BIODERMA-ATODERM-CREAM",
      name: "Atoderm Crème",
      brand: "Bioderma",
      brandCountry: "Francia",
      category: "skincare",
      productType: "cream",
      description: "Crema idratante per pelli molto secche e sensibili. Ripara la barriera cutanea.",
      ingredients: "Ceramidi, Niacinamide, Shega Science",
      keyIngredients: "Ceramidi, Niacinamide",
      skinTypes: "dry, very dry, sensitive",
      skinConcerns: "idratazione, secchezza, barriera",
      price: 16.90,
      size: "500ml",
      rating: 4.6,
      reviewCount: 5678,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://images.unsplash.com/photo-1570194065650-d99fb4b38c34?w=400&h=400&fit=crop",
      officialUrl: "https://www.bioderma.it/atoderm-creme",
      amazonUrl: "https://www.amazon.it/dp/B00I7VH9GS",
    },

    // ==================== VICHY - Francia (SITO ITALIANO) ====================
    {
      productId: "VICHY-MINERAL-89",
      name: "Minéral 89 Hyaluronic Acid",
      brand: "Vichy",
      brandCountry: "Francia",
      category: "skincare",
      productType: "serum",
      description: "Booster idratante con acqua termale di Vichy 89% e acido ialuronico. Rinforza la barriera cutanea.",
      ingredients: "Vichy Volcanic Water 89%, Sodium Hyaluronate, Glycerin",
      keyIngredients: "Vichy Volcanic Water 89%, Hyaluronic Acid",
      skinTypes: "all, sensitive",
      skinConcerns: "idratazione, barriera, sensibilità",
      price: 19.90,
      size: "50ml",
      rating: 4.6,
      reviewCount: 3456,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=400&fit=crop",
      officialUrl: "https://www.vichy.it/mineral-89",
      amazonUrl: "https://www.amazon.it/dp/B079NG3W7J",
    },
    {
      productId: "VICHY-NORMADERM-PHYTO",
      name: "Normaderm Phytosolution",
      brand: "Vichy",
      brandCountry: "Francia",
      category: "skincare",
      productType: "treatment",
      description: "Trattamento correttivo per pelli con imperfezioni con acido salicilico e probiotici.",
      ingredients: "Salicylic Acid, Probiotics, Zinc, Vichy Thermal Water",
      keyIngredients: "Salicylic Acid, Probiotics, Zinc",
      skinTypes: "oily, acne-prone",
      skinConcerns: "acne, imperfezioni, pori",
      price: 18.90,
      size: "50ml",
      rating: 4.4,
      reviewCount: 2345,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop",
      officialUrl: "https://www.vichy.it/normaderm-phytosolution",
      amazonUrl: "https://www.amazon.it/dp/B00TQZ7HVA",
    },

    // ==================== THE ORDINARY - Canada ====================
    {
      productId: "ORD-NIACINAMIDE-10-ZINC-1",
      name: "Niacinamide 10% + Zinc 1%",
      brand: "The Ordinary",
      brandCountry: "Canada",
      category: "skincare",
      productType: "serum",
      description: "Siero con Niacinamide 10% e Zinc 1% per ridurre pori e imperfezioni.",
      ingredients: "Niacinamide 10%, Zinc PCA 1%, Pentylene Glycol",
      keyIngredients: "Niacinamide 10%, Zinc 1%",
      skinTypes: "oily, combination",
      skinConcerns: "pori, sebo, acne, imperfezioni",
      price: 6.90,
      size: "30ml",
      rating: 4.5,
      reviewCount: 8934,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=400&fit=crop",
      officialUrl: "https://theordinary.com/it-it/products/niacinamide-10pct-zinc-1pct",
      sephoraUrl: "https://www.sephora.it/p/niacinamide-10-zinc-1-P454366.html",
      amazonUrl: "https://www.amazon.it/dp/B06XKXVQZS",
    },
    {
      productId: "ORD-RETINOL-05-SQUALANE",
      name: "Retinol 0.5% in Squalane",
      brand: "The Ordinary",
      brandCountry: "Canada",
      category: "skincare",
      productType: "treatment",
      description: "Trattamento anti-età con Retinolo 0.5% in olio di squalano.",
      ingredients: "Retinol 0.5%, Squalane, Caprylic/Capric Triglyceride",
      keyIngredients: "Retinol 0.5%, Squalane",
      skinTypes: "normal, combination, dry",
      skinConcerns: "anti-età, rughe, texture",
      price: 8.90,
      size: "30ml",
      rating: 4.4,
      reviewCount: 5678,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop",
      officialUrl: "https://theordinary.com/it-it/products/retinol-0-5-in-squalane",
      amazonUrl: "https://www.amazon.it/dp/B079NGH2JT",
    },
    {
      productId: "ORD-HYALURONIC-ACID-2-B5",
      name: "Hyaluronic Acid 2% + B5",
      brand: "The Ordinary",
      brandCountry: "Canada",
      category: "skincare",
      productType: "serum",
      description: "Siero idratante con acido ialuronico multi-peso molecolare 2% e Vitamina B5.",
      ingredients: "Sodium Hyaluronate Crosspolymer 2%, Panthenol 1%",
      keyIngredients: "Hyaluronic Acid 2%, Vitamin B5",
      skinTypes: "all, dehydrated",
      skinConcerns: "idratazione, disidratazione",
      price: 7.90,
      size: "30ml",
      rating: 4.5,
      reviewCount: 6789,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=400&fit=crop",
      officialUrl: "https://theordinary.com/it-it/products/hyaluronic-acid-2-b5",
      amazonUrl: "https://www.amazon.it/dp/B06XKXVQP2",
    },
    {
      productId: "ORD-ALPHA-ARBUTIN-2-HA",
      name: "Alpha Arbutin 2% + HA",
      brand: "The Ordinary",
      brandCountry: "Canada",
      category: "skincare",
      productType: "serum",
      description: "Siero schiarente con Alpha-Arbutin 2% per ridurre macchie e iperpigmentazione.",
      ingredients: "Alpha-Arbutin 2%, Hyaluronic Acid",
      keyIngredients: "Alpha-Arbutin 2%, Hyaluronic Acid",
      skinTypes: "all",
      skinConcerns: "macchie, iperpigmentazione, uniformità",
      price: 9.90,
      size: "30ml",
      rating: 4.4,
      reviewCount: 3456,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=400&fit=crop",
      officialUrl: "https://theordinary.com/it-it/products/alpha-arbutin-2pct-ha",
      amazonUrl: "https://www.amazon.it/dp/B06XKXVQQF",
    },

    // ==================== CERAVE - USA ====================
    {
      productId: "CERAVE-HYDRATING-CLEANSER",
      name: "Hydrating Facial Cleanser",
      brand: "CeraVe",
      brandCountry: "USA",
      category: "skincare",
      productType: "cleanser",
      description: "Detergente idratante con ceramidi e acido ialuronico. Non schiumogeno.",
      ingredients: "Ceramide NP, Ceramide AP, Ceramide EOP, Hyaluronic Acid",
      keyIngredients: "Ceramides 1, 3, 6-II, Hyaluronic Acid",
      skinTypes: "dry, sensitive, normal",
      skinConcerns: "idratazione, barriera, sensibilità, detersione",
      price: 14.00,
      size: "236ml",
      rating: 4.7,
      reviewCount: 12453,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop",
      officialUrl: "https://www.cerave.com/hydrating-facial-cleanser",
      amazonUrl: "https://www.amazon.it/dp/B00I7VH9GS",
    },
    {
      productId: "CERAVE-MOISTURIZING-CREAM",
      name: "Moisturizing Cream",
      brand: "CeraVe",
      brandCountry: "USA",
      category: "skincare",
      productType: "cream",
      description: "Crema idratante con ceramidi e acido ialuronico. Formula ricca per pelli molto secche.",
      ingredients: "Ceramide NP, Ceramide AP, Ceramide EOP, Hyaluronic Acid, Petrolatum",
      keyIngredients: "Ceramides, Hyaluronic Acid, Petrolatum",
      skinTypes: "dry, very dry, normal, sensitive",
      skinConcerns: "idratazione, barriera, secchezza",
      price: 18.00,
      size: "453g",
      rating: 4.8,
      reviewCount: 15678,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://images.unsplash.com/photo-1570194065650-d99fb4b38c34?w=400&h=400&fit=crop",
      officialUrl: "https://www.cerave.com/moisturizing-cream",
      amazonUrl: "https://www.amazon.it/dp/B001VBSBSG",
    },

    // ==================== PAULA'S CHOICE - USA ====================
    {
      productId: "PC-BHA-2-LIQUID",
      name: "Skin Perfecting 2% BHA Liquid Exfoliant",
      brand: "Paulas Choice",
      brandCountry: "USA",
      category: "skincare",
      productType: "exfoliant",
      description: "Esfoliante liquido con acido salicilico 2%. Illumina la pelle, riduce pori e punti neri.",
      ingredients: "Salicylic Acid 2%, Green Tea Extract, Butylene Glycol",
      keyIngredients: "Salicylic Acid 2%, Green Tea Extract",
      skinTypes: "oily, combination, acne-prone",
      skinConcerns: "pori, acne, texture, punti neri",
      price: 35.00,
      size: "118ml",
      rating: 4.7,
      reviewCount: 6789,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop",
      officialUrl: "https://www.paulaschoice.com/skin-perfecting-2pct-bha-liquid-exfoliant",
      sephoraUrl: "https://www.sephora.it/p/skin-perfecting-2-bha-liquid-exfoliant-P454376.html",
      amazonUrl: "https://www.amazon.it/dp/B00NTTHTXO",
    },

    // ==================== HADA LABO - Giappone ====================
    {
      productId: "HADALABO-GOKUJYUN-PREMIUM",
      name: "Gokujyun Premium Hyaluronic Acid Lotion",
      brand: "Hada Labo",
      brandCountry: "Giappone",
      category: "skincare",
      productType: "toner",
      description: "Lozione con 7 tipi di acido ialuronico. Idratazione profonda per tutti gli strati della pelle.",
      ingredients: "Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Sodium Acetylated Hyaluronate",
      keyIngredients: "7 Types of Hyaluronic Acid",
      skinTypes: "all, dry, dehydrated",
      skinConcerns: "idratazione, disidratazione",
      price: 15.00,
      size: "170ml",
      rating: 4.8,
      reviewCount: 5678,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: false,
      imageUrl: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop",
      officialUrl: "https://hadalabo.us/products/gokujyun-premium-hyaluronic-acid-lotion",
      amazonUrl: "https://www.amazon.it/dp/B07V5QT1LJ",
    },

    // ==================== OLAPLEX - USA ====================
    {
      productId: "OLAPLEX-NO3",
      name: "No.3 Hair Perfector",
      brand: "Olaplex",
      brandCountry: "USA",
      category: "haircare",
      productType: "treatment",
      description: "Trattamento riparatore professionale per capelli danneggiati.",
      ingredients: "Bis-Aminopropyl Diglycol Dimaleate, Propylene Glycol",
      keyIngredients: "Bis-Aminopropyl Diglycol Dimaleate",
      hairTypes: "damaged, colored, treated",
      hairConcerns: "danni, rottura, trattamenti chimici",
      price: 32.00,
      size: "100ml",
      rating: 4.8,
      reviewCount: 8976,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop",
      officialUrl: "https://www.olaplex.com/products/no-3-hair-perfector",
      sephoraUrl: "https://www.sephora.it/p/olaplex-hair-perfector-no-3-P454227.html",
      amazonUrl: "https://www.amazon.it/dp/B00TQZ7HTS",
    },

    // ==================== SK-II - Giappone ====================
    {
      productId: "SKII-FTE",
      name: "Facial Treatment Essence",
      brand: "SK-II",
      brandCountry: "Giappone",
      category: "skincare",
      productType: "essence",
      description: "Essenza leggendaria con PITERA 90%. Illumina, idrata e migliora la texture cutanea.",
      ingredients: "Galactomyces Ferment Filtrate 90%, Butylene Glycol",
      keyIngredients: "PITERA 90%, Galactomyces Ferment Filtrate",
      skinTypes: "all",
      skinConcerns: "luminosità, texture, anti-età",
      price: 99.00,
      size: "75ml",
      rating: 4.7,
      reviewCount: 3456,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=400&fit=crop",
      officialUrl: "https://www.sk-ii.com/facial-treatment-essence",
      sephoraUrl: "https://www.sephora.it/p/sk-ii-facial-treatment-essence-P454247.html",
    },

    // ==================== ESTÉE LAUDER - USA ====================
    {
      productId: "ESTEE-ANR",
      name: "Advanced Night Repair Serum",
      brand: "Estee Lauder",
      brandCountry: "USA",
      category: "skincare",
      productType: "serum",
      description: "Siero notturno riparatore con tecnologia ChronoluxCB. Riduce rughe e migliora l'elasticità.",
      ingredients: "Bifida Ferment Lysate, Tripeptide-32, Sodium Hyaluronate",
      keyIngredients: "ChronoluxCB, Bifida Ferment Lysate",
      skinTypes: "all",
      skinConcerns: "anti-età, riparazione, rughe",
      price: 89.00,
      size: "30ml",
      rating: 4.8,
      reviewCount: 5678,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: false,
      imageUrl: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=400&fit=crop",
      officialUrl: "https://www.esteelauder.com/advanced-night-repair",
      sephoraUrl: "https://www.sephora.it/p/estee-lauder-advanced-night-repair-P454257.html",
    },

    // ==================== DRUNK ELEPHANT - USA ====================
    {
      productId: "DRUNK-PROTINI",
      name: "Protini Polypeptide Cream",
      brand: "Drunk Elephant",
      brandCountry: "USA",
      category: "skincare",
      productType: "cream",
      description: "Crema viso con peptidi e acido ialuronico. Texture gel-crema leggera ma idratante.",
      ingredients: "Pygmy Waterlily, Peptides, Sodium Hyaluronate",
      keyIngredients: "Peptides, Hyaluronic Acid, Pygmy Waterlily",
      skinTypes: "all",
      skinConcerns: "anti-età, elasticità, idratazione",
      price: 68.00,
      size: "50ml",
      rating: 4.5,
      reviewCount: 3456,
      isKorean: false,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://images.unsplash.com/photo-1570194065650-d99fb4b38c34?w=400&h=400&fit=crop",
      officialUrl: "https://drunkelephant.com/products/protini-polypeptide-cream",
      sephoraUrl: "https://www.sephora.it/p/drunk-elephant-protini-polypeptide-cream-P454267.html",
    },

    // ==================== L'ERBOLARIO - Italia ====================
    {
      productId: "LERBOLARIO-MANDORLA-CREAM",
      name: "Crema Mandorla",
      brand: "L'Erbolario",
      brandCountry: "Italia",
      category: "skincare",
      productType: "cream",
      description: "Crema idratante con olio di mandorle dolci e vitamina E. Delicata e nutriente.",
      ingredients: "Sweet Almond Oil, Vitamin E, Shea Butter",
      keyIngredients: "Sweet Almond Oil, Vitamin E",
      skinTypes: "dry, normal, sensitive",
      skinConcerns: "idratazione, nutrizione, delicatezza",
      price: 24.00,
      size: "250ml",
      rating: 4.6,
      reviewCount: 1234,
      isKorean: false,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://images.unsplash.com/photo-1570194065650-d99fb4b38c34?w=400&h=400&fit=crop",
      officialUrl: "https://www.lerbolario.com/crema-mandorla",
      amazonUrl: "https://www.amazon.it/dp/B00TQZ7HXW",
    },

    // ==================== New K-Beauty from MiiN ====================
    {
      productId: "ONDO-CERAMIDES-SUN-SPF50",
      name: "Ceramides & Cica Protective Sun Cream SPF50+",
      brand: "Ondo Beauty 36.5",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "spf",
      description: "Crema solare con protezione 50 idratante e antiossidante. Adatta a tutti i tipi di pelle.",
      ingredients: "Ceramides, Cica, Niacinamide, Zinc Oxide",
      keyIngredients: "Ceramides, Cica, Niacinamide",
      skinTypes: "all, sensitive",
      skinConcerns: "protezione solare, idratazione, calmante",
      price: 29.90,
      size: "50ml",
      rating: 4.7,
      reviewCount: 892,
      isKorean: true,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.it/8698-product_zoom/ceramides-cica-protective-sun-cream.jpg",
      officialUrl: "https://ondobeauty.com/",
      miinUrl: "https://miin-cosmetics.it/1076-ceramides-cica-protective-sun-cream.html",
    },
    {
      productId: "SKIN1004-CENTELLA-CLEANSING-OIL",
      name: "Madagascar Centella Light Cleansing Oil",
      brand: "SKIN1004",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "cleanser",
      description: "Detergente oleoso leggero con Centella Asiatica. Rimuove trucco e impurità senza seccare la pelle.",
      ingredients: "Centella Asiatica Extract, Squalane, Olive Oil, Jojoba Oil",
      keyIngredients: "Centella Asiatica 30%, Squalane",
      skinTypes: "all, sensitive, combination",
      skinConcerns: "detersione, make-up removal, idratazione",
      price: 22.90,
      size: "200ml",
      rating: 4.6,
      reviewCount: 2341,
      isKorean: true,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.it/6720-product_zoom/madagascar-centella-light-cleansing-oil.jpg",
      officialUrl: "https://skin1004.com/",
      miinUrl: "https://miin-cosmetics.it/1387-madagascar-centella-light-cleansing-oil.html",
    },
    {
      productId: "SUNTIQUE-VEGAN-SUN-SERUM",
      name: "I'm Vegan Sun Serum SPF50+ PA++++",
      brand: "Suntique",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "spf",
      description: "Siero solare vegano SPF50+ con protezione ad ampio spettro. Texture leggera e trasparente.",
      ingredients: "Centella Asiatica, Green Tea, Vitamin E, Aloe Vera",
      keyIngredients: "Centella Asiatica, Green Tea, Vitamin E",
      skinTypes: "all, sensitive",
      skinConcerns: "protezione solare, antiossidante, idratazione",
      price: 26.00,
      size: "50ml",
      rating: 4.5,
      reviewCount: 1567,
      isKorean: true,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.it/9783-product_zoom/i-m-vegan-sun-serum-spf50-pa.jpg",
      officialUrl: "https://suntique.co.kr/",
      miinUrl: "https://miin-cosmetics.it/878-i-m-vegan-sun-serum-spf50-pa.html",
    },
    {
      productId: "MEISANI-NIACINAMIDE-GEL-CREAM",
      name: "Niacinamide Cucumber Aqua Gel Cream",
      brand: "Meisani",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "moisturizer",
      description: "Gel-crema idratante con Niacinamide 4% e cetriolo. Opacizzante e illuminante per pelli miste-grasse.",
      ingredients: "Niacinamide, Cucumber Extract, Hyaluronic Acid, Panthenol",
      keyIngredients: "Niacinamide 4%, Cucumber Extract, HA",
      skinTypes: "combination, oily, normal",
      skinConcerns: "idratazione, sebo regolatore, pori",
      price: 24.90,
      size: "60ml",
      rating: 4.4,
      reviewCount: 789,
      isKorean: true,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.it/8674-product_zoom/niacinamide-cucumber-aqua-gel-cream.jpg",
      officialUrl: "https://meisani.com/",
      miinUrl: "https://miin-cosmetics.it/884-niacinamide-cucumber-aqua-gel-cream.html",
    },
    {
      productId: "ONDO-PAPAYA-CLEANSING-BALM",
      name: "Multiacids & Papaya Melting Cleansing Balm",
      brand: "Ondo Beauty 36.5",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "cleanser",
      description: "Balm detergente con AHA, BHA e papaya. Scioglie il trucco e esfolia delicatamente.",
      ingredients: "Papaya Extract, Lactic Acid, Salicylic Acid, Squalane",
      keyIngredients: "Papaya Enzyme, AHA, BHA",
      skinTypes: "all, dry, normal",
      skinConcerns: "detersione, esfoliazione, make-up removal",
      price: 28.00,
      size: "100ml",
      rating: 4.5,
      reviewCount: 634,
      isKorean: true,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.it/8725-product_zoom/multiacids-papaya-melting-cleansing-balm.jpg",
      officialUrl: "https://ondobeauty.com/",
      miinUrl: "https://miin-cosmetics.it/947-multiacids-papaya-melting-cleansing-balm.html",
    },
    {
      productId: "BARR-CENTELLA-SUN-ESSENCE",
      name: "Centella Soothing Sun Essence SPF50+",
      brand: "Barr",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "spf",
      description: "Essenza solare con Centella Asiatica SPF50+. Protezione leggera e lenitiva.",
      ingredients: "Centella Asiatica, Niacinamide, Hyaluronic Acid",
      keyIngredients: "Centella Asiatica, Niacinamide",
      skinTypes: "all, sensitive",
      skinConcerns: "protezione solare, calmante, idratazione",
      price: 25.00,
      size: "50ml",
      rating: 4.6,
      reviewCount: 445,
      isKorean: true,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.it/4832-product_zoom/centella-soothing-sun-essence.jpg",
      officialUrl: "https://barr.co.kr/",
      miinUrl: "https://miin-cosmetics.it/982-centella-soothing-sun-essence.html",
    },
    {
      productId: "BELIF-TRUE-CREAM",
      name: "The True Cream Moisturizing Bomb",
      brand: "Belif",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "moisturizer",
      description: "Crema idratante intensiva con texture leggera. Formula erboristica per idratazione profonda 26h.",
      ingredients: "Shea Butter, Apricot Kernel Oil, Rosemary Leaf Oil",
      keyIngredients: "Shea Butter, Apricot Kernel Oil, Aqua Herbal Formula",
      skinTypes: "dry, normal, combination",
      skinConcerns: "idratazione, secchezza, barriera cutanea",
      price: 35.00,
      size: "50ml",
      rating: 4.7,
      reviewCount: 5432,
      isKorean: true,
      isVegan: false,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.it/6355-product_zoom/the-true-cream-moisturizing-bomb-.jpg",
      officialUrl: "https://www.belifcosmetics.com/",
      miinUrl: "https://miin-cosmetics.it/1254-the-true-cream-moisturizing-bomb-.html",
    },
    {
      productId: "LAKA-BONDING-LIPSTICK",
      name: "Bonding Glow Lipstick",
      brand: "Laka",
      brandCountry: "Corea del Sud",
      category: "makeup",
      productType: "lipstick",
      description: "Rossetto vegano con finish glow. Formula leggera idratante con colore costruibile.",
      ingredients: "Shea Butter, Jojoba Oil, Vitamin E, Rice Bran Oil",
      keyIngredients: "Shea Butter, Jojoba Oil, Vitamin E",
      price: 18.00,
      size: "3.5g",
      rating: 4.3,
      reviewCount: 1234,
      isKorean: true,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.it/6425-product_zoom/bonding-glow-lipstick.jpg",
      officialUrl: "https://laka.kr/",
      miinUrl: "https://miin-cosmetics.it/1291-bonding-glow-lipstick.html",
    },
    {
      productId: "SKIN1004-ALOE-SOOTHING-MASK",
      name: "Aloe Soothing Mask",
      brand: "SKIN1004",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "mask",
      description: "Maschera viso in tessuto con aloe vera per pelli sensibili. Lenitiva e idratante.",
      ingredients: "Aloe Barbadensis Leaf Extract, Centella Asiatica, Green Tea",
      keyIngredients: "Aloe Vera 90%, Centella Asiatica",
      skinTypes: "all, sensitive, dry",
      skinConcerns: "calmante, idratazione, arrossamenti",
      price: 3.50,
      size: "20ml",
      rating: 4.4,
      reviewCount: 3456,
      isKorean: true,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.it/5168-product_zoom/aloe-soothing-mask.jpg",
      officialUrl: "https://skin1004.com/",
      miinUrl: "https://miin-cosmetics.it/480-aloe-soothing-mask.html",
    },
    {
      productId: "HARUHARU-BLACK-RICE-TONER",
      name: "Black Rice Hyaluronic Toner",
      brand: "HaruHaru Wonder",
      brandCountry: "Corea del Sud",
      category: "skincare",
      productType: "toner",
      description: "Tonico idratante al riso nero e acido ialuronico. Texture leggera che prepara la pelle.",
      ingredients: "Black Rice Extract 42%, Hyaluronic Acid, Glycerin, Panthenol",
      keyIngredients: "Black Rice Extract 42%, Hyaluronic Acid",
      skinTypes: "all, dry, normal, combination",
      skinConcerns: "idratazione, illuminante, barriera cutanea",
      price: 21.00,
      size: "150ml",
      rating: 4.6,
      reviewCount: 2876,
      isKorean: true,
      isVegan: true,
      isCrueltyFree: true,
      imageUrl: "https://miin-cosmetics.it/8926-product_zoom/rice-toner.jpg",
      officialUrl: "https://haruharuwonder.com/",
      miinUrl: "https://miin-cosmetics.it/1948-rice-toner.html",
    },
  ];
